### ISSUE TITLE
$_EXTKEY must be used in ext_emconf

### ISSUE THREAD

**Issue by georgringer** [colorcube/dummy_content#2]
please don't use `$EM_CONF['dummy_content']` but `$EM_CONF[$_EXTKEY]` as this can lead otherwise to strange situations. this is not yet resolved completly in the core

**Comment by colorcube** [comment]
Thanks for the hint. I thought I read somewhere that $_EXTKEY is deprecated.
Anyway, fixed in v1.3.1

**Comment by georgringer** [comment]
yes deprecated and not in use in ext_localconf/ext_tables
